# Generated by Django 2.1.7 on 2019-06-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested_documents',
            name='lesson',
        ),
    ]
