# Generated by Django 2.1.4 on 2019-01-17 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Sınav Türü')),
                ('exam_information', models.TextField(max_length=500, verbose_name='Sınav Hakkında Bilgi')),
                ('exam_file', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Sınav Kağıdı Dosya')),
                ('exam_answer_file', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Cevap Anahtarı Dosya')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=150, verbose_name='Ders Adı')),
                ('lesson_content', models.TextField(blank=True, verbose_name='Ders İçeriği')),
                ('lesson_content_file', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Ders İçeriği Dosya')),
                ('lesson_notes', models.TextField(blank=True, verbose_name='Ders Notu')),
                ('lesson_notes_file', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Ders Notu Dosya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Other_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_evaluation_form', models.FileField(upload_to=edms.models.set_user_files_upload_path, verbose_name='Ders Değerlendirme Formu')),
                ('course_survey', models.FileField(upload_to='', verbose_name='Ders Anketi')),
                ('exam_note_list_midterm', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Arasınav Sınav Not Listesi')),
                ('exam_note_list_end_of_term', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Dönem Sonu Sınav Not Listesi')),
                ('exam_note_list_Integrated', models.FileField(blank=True, null=True, upload_to=edms.models.set_user_files_upload_path, verbose_name='Bütünleme Sınav Not Listesi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edms.Lesson')),
            ],
            options={
                'verbose_name': 'Other Document',
                'verbose_name_plural': 'Other Document',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edms.Lesson'),
        ),
    ]
