# Generated by Django 2.1.4 on 2018-12-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_information',
            field=models.TextField(max_length=500, verbose_name='Sınav Hakkında Bilgi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.TextField(max_length=50, verbose_name='Sınav Türü'),
        ),
    ]
