# Generated by Django 2.1.4 on 2019-01-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requested_Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100, verbose_name='İstenilen Belge Adı')),
                ('d_bool', models.BooleanField(default=False, verbose_name='İstenilen Belge Yüklü mü ?')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edms.Lesson')),
            ],
            options={
                'verbose_name': 'Requested Documents',
                'verbose_name_plural': 'Requested Documents',
            },
        ),
    ]
