# Generated by Django 2.1.7 on 2019-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_read',
            field=models.BooleanField(default=False, verbose_name='Admin read?'),
        ),
    ]
